version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: fain-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: FAIN
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spring:
    build:
      context: ../FAIN_BE 
    container_name: fain-spring
    ports:
      - "8080:8080"
    env_file:
      - ../secrets/spring.env
    volumes:
      - ../secrets/firebase-service-account.json:/app/firebase/firebase-service-account.json
    depends_on:
      - mysql

  python:
    build:
      context: ../FAIN_BE_PY  # python 레포 위치에 맞게 수정!
    container_name: fain-python
    ports:
      - "8000:8000"
    env_file:
      - ../secrets/python.env

volumes:
  mysql-data:
